"""
Reads schemes*.csv / eligibility_rules*.csv / required_documents*.csv from
this directory (base files plus any _batchN suffix) and emits seed.sql.
Per DATASET_PLAN.md Step 5 — a disposable generated artifact, re-run whenever
the CSVs change. The CSVs are the source of truth.

IMPORTANT when importing seed.sql: XAMPP's mysql.exe on Windows defaults to
the cp850 client charset, which silently mangles non-ASCII characters (₹,
etc.) on INSERT even though the table is utf8mb4. Always import with:
    mysql -u root saarthi_db --default-character-set=utf8mb4 < seed.sql
"""
import csv
import glob
import os

SEED_DIR = os.path.dirname(os.path.abspath(__file__))


def sql_str(value):
    if value is None or value.strip() == "":
        return "NULL"
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def sql_bool(value):
    return "TRUE" if value.strip().lower() in ("true", "1", "yes") else "FALSE"


def sql_date(value):
    return "NULL" if not value or not value.strip() else f"'{value.strip()}'"


def load_rows(pattern):
    rows = []
    for path in sorted(glob.glob(os.path.join(SEED_DIR, pattern))):
        with open(path, newline="", encoding="utf-8-sig") as f:
            for row in csv.DictReader(f):
                rows.append(row)
    return rows


def main():
    schemes = load_rows("schemes*.csv")
    rules = load_rows("eligibility_rules*.csv")
    documents = load_rows("required_documents*.csv")

    seen_names = set()
    deduped_schemes = []
    for s in schemes:
        name = s["name"].strip()
        if name in seen_names:
            print(f"WARNING: duplicate scheme name skipped: {name}")
            continue
        seen_names.add(name)
        deduped_schemes.append(s)

    lines = []
    lines.append("-- Generated by import_seed.py — do not hand-edit, edit the CSVs instead.")
    lines.append("START TRANSACTION;")
    lines.append("")

    lines.append("-- ===== schemes =====")
    for s in deduped_schemes:
        name = s["name"].strip()
        state = s["state"].strip() if s.get("state") else ""
        lines.append(
            "INSERT INTO schemes "
            "(name, description, ministry, category_id, state, benefit_summary, benefit_amount, "
            "application_url, official_portal, is_active, source_url, verified_at) VALUES ("
            f"{sql_str(name)}, {sql_str(s.get('benefit_summary'))}, {sql_str(s['ministry'])}, "
            f"(SELECT category_id FROM scheme_categories WHERE category_name = {sql_str(s['category'])}), "
            f"{sql_str(state)}, {sql_str(s.get('benefit_summary'))}, {sql_str(s.get('benefit_amount'))}, "
            f"{sql_str(s.get('application_url'))}, {sql_str(s.get('official_portal'))}, "
            f"{sql_bool(s.get('is_active', 'true'))}, {sql_str(s.get('source_url'))}, {sql_date(s.get('verified_at'))});"
        )
    lines.append("")

    lines.append("-- ===== eligibility_rules =====")
    for r in rules:
        scheme_name = r["scheme_name"].strip()
        if scheme_name not in seen_names:
            print(f"WARNING: rule for unknown scheme skipped: {scheme_name}")
            continue
        lines.append(
            "INSERT INTO eligibility_rules "
            "(scheme_id, attribute_name, operator, value, rule_description, source_text_snippet) VALUES ("
            f"(SELECT scheme_id FROM schemes WHERE name = {sql_str(scheme_name)}), "
            f"{sql_str(r['attribute_name'])}, {sql_str(r['operator'])}, {sql_str(r['value'])}, "
            f"{sql_str(r.get('rule_description'))}, {sql_str(r.get('source_text_snippet'))});"
        )
    lines.append("")

    lines.append("-- ===== required_documents =====")
    for d in documents:
        scheme_name = d["scheme_name"].strip()
        if scheme_name not in seen_names:
            print(f"WARNING: document for unknown scheme skipped: {scheme_name}")
            continue
        lines.append(
            "INSERT INTO required_documents (scheme_id, document_name, document_category, is_mandatory) VALUES ("
            f"(SELECT scheme_id FROM schemes WHERE name = {sql_str(scheme_name)}), "
            f"{sql_str(d['document_name'])}, {sql_str(d.get('document_category'))}, {sql_bool(d.get('is_mandatory', 'true'))});"
        )
    lines.append("")
    lines.append("COMMIT;")

    out_path = os.path.join(SEED_DIR, "seed.sql")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {out_path}")
    print(f"Schemes: {len(deduped_schemes)}, Rules: {len(rules)}, Documents: {len(documents)}")


if __name__ == "__main__":
    main()
